sudo: false
language: php
php:
# Commenting out outdated PHP versions for now, will fix in
#  - 5.6
#  - 7
#  - 7.1
  - 7.2

install:
  - composer install

script:
  - composer cs
  - composer test

cache:
  directories:
    - $HOME/.composer/cache/files
